window.__BKK_DICT__ = {
  "title": { zh: "曼谷五天", en: "Bangkok, Five Days" },
"subtitle": { zh: "輕鬆行程，純粹 Guide", en: "A relaxed itinerary — just a guide" },
  "f1k": { zh: "日期", en: "Dates" },
"f2k": { zh: "住宿", en: "Staying at" },
  "wed": { zh: "三", en: "Wed" }, "thu": { zh: "四", en: "Thu" }, "fri": { zh: "五", en: "Fri" },
"sat": { zh: "六", en: "Sat" }, "sun": { zh: "日", en: "Sun" },
"morning": { zh: "上午", en: "Morning" },
"afternoon": { zh: "下午", en: "Afternoon" },
"evening": { zh: "晚上", en: "Evening" },
"daytime": { zh: "白天", en: "Daytime" },
"dusk": { zh: "傍晚", en: "Early evening" },
  "byflight-hk": { zh: "依航班", en: "Per flight" },
  "friendsdinner": { zh: "晚餐", en: "Dinner" },
"massage": { zh: "按摩", en: "Massage" },
"walkin": { zh: "免訂位", en: "No booking" },
  "date-930": { zh: "9/30", en: "30 Sep" },
  "date-101": { zh: "10/1", en: "1 Oct" },
  "date-102": { zh: "10/2", en: "2 Oct" },
  "date-103": { zh: "10/3", en: "3 Oct" },
  "date-104": { zh: "10/4", en: "4 Oct" },
  "dates-range": { zh: "9/30 – 10/4", en: "30 Sep – 4 Oct" },
  "d1-title": { zh: "抵達", en: "Arrival" },
"d1-0-h": { zh: "Hank 抵達", en: "Hank arrives" },
  "d1-0-p": { zh: "香港飛曼谷，時間與 Grace 相近，機場碰面。", en: "Flying in from Hong Kong, similar time to Grace — meeting at the airport." },
  "d1-1-h": { zh: "Grace 抵達", en: "Grace arrives" },
  "d1-1-p": { zh: "桃園飛曼谷，落地 16:20。", en: "Flying Taoyuan → Bangkok, landing 4:20 PM." },
  "d1-transit-h": { zh: "機場 → 飯店", en: "Airport → hotel" },
  "d1-transit-p": { zh: "Airport Rail Link 到 Phaya Thai（26分鐘，45泰銖），轉 BTS Sukhumvit 線（同系統免出站）坐到 Thong Lo 站，步行約 5-10 分鐘到飯店。全程約 50-60 分鐘。", en: "Airport Rail Link to Phaya Thai (26 min, 45 THB), then BTS Sukhumvit Line (same system, no exit needed) to Thong Lo station, 5-10 min walk to the hotel. About 50-60 minutes total." },
  "d1-3-h": { zh: "Day2 按摩訂位", en: "Book Day 2 massage" },
  "d1-3-p": { zh: "路過 Sakura Spa 或 White Wood Green 時現場訂明天下午時段。", en: "Book tomorrow afternoon's slot in person at Sakura Spa or White Wood Green when passing by." },
  "d1-2-p": { zh: "朋友聚餐，自行安排，時間留白。", en: "Dinner with friends, self-arranged, kept open." },
  "d2-title": { zh: "Thonglor：運動・按摩・自然酒", en: "Thonglor: sport, spa, natural wine" },
  "d2-1-h": { zh: "Benjakitti Forest Park", en: "Benjakitti Forest Park" },
  "d2-1-p": { zh: "跑步。BTS Thong Lo → Asok，兩站，步行 5 分鐘進公園。", en: "Run. BTS Thong Lo → Asok, two stops, 5-minute walk into the park." },
  "d2-2-h": { zh: "飯店休息游泳", en: "Rest & swim at the hotel" },
  "d2-3-h": { zh: "午餐", en: "Lunch" },
"d2-3-p": { zh: "Thonglor 街區，不特別安排。", en: "Around Thonglor, nothing specific planned." },
  "d2-4-p": { zh: "Sakura Spa 或 White Wood Green，90 分鐘。", en: "Sakura Spa or White Wood Green, 90 minutes." },
  "d2-5-p": { zh: "自然酒，晚餐前。", en: "Natural wine, before dinner." },
  "d2-6-p": { zh: "朋友聚餐，自行安排，時間留白。", en: "Dinner with friends, self-arranged, kept open." },
  "d3-title": { zh: "MOCA・藝術設計・iODE", en: "MOCA, art & design, iODE" },
  "d3-1-p": { zh: "車程 30-45 分鐘，無 BTS 直達。", en: "30-45 minutes by car, no direct BTS." },
  "d3-2-p": { zh: "National Stadium 站附近，與 BACC 步行 10 分鐘內。", en: "Near National Stadium station, under 10 minutes on foot from BACC." },
  "d3-3-h": { zh: "午餐", en: "Lunch" },
"d3-3-p": { zh: "Siam 一帶，不特別安排。", en: "Around Siam, nothing specific planned." },
  "d3-4-p": { zh: "曼谷藝術文化中心，National Stadium 站對面。今年雙年展 10/22 開展，尚未開放。", en: "Bangkok Art and Culture Centre, across from National Stadium station. This year's Biennale opens 10/22 — not yet running." },
  "d3-5-h": { zh: "Siam Square", en: "Siam Square" },
  "d3-5-p": { zh: "逛街 + 小吃，約 1.5 小時。", en: "Shopping and street food, about 1.5 hours." },
  "d3-arch-h": { zh: "沿途建築", en: "Architecture along the way" },
  "d3-arch-p": { zh: "BACC 本身是螺旋動線的清水模建築；Jim Thompson House 是傳統泰式柚木高腳屋。晚上往 Sathorn 移動時，會經過 King Power MahaNakhon（Ole Scheeren 設計，曼谷地標高樓）。", en: "BACC itself is a spiral-ramp raw-concrete building; Jim Thompson House is a traditional Thai teak stilt house. Heading to Sathorn in the evening, you'll pass King Power MahaNakhon (designed by Ole Scheeren, Bangkok's landmark tower)." },
  "reserved-2000": { zh: "已訂位 20:00", en: "Reserved 8:00 PM" },
  "d3-6-p": { zh: "Sathorn / Lumphini。Siam 過去車程 20-30 分鐘，留寬裕時間。", en: "Sathorn / Lumphini. 20-30 minutes from Siam — leave room to spare." },
  "reserved-2200": { zh: "已訂位 22:00", en: "Reserved 10:00 PM" },
  "d3-7-p": { zh: "W Bangkok 內，與 iODE 同區。50 Best #17。", en: "Inside W Bangkok, same area as iODE. Asia's 50 Best Bars #17." },
  "d4-1-p": { zh: "園區遊園巴士，不需自行開車。車程單趟 45-60 分鐘，無 BTS 直達。野生動物區 + 海洋世界，午餐可在園內解決。", en: "Park's own tour bus — no need to drive. 45-60 minutes each way, no direct BTS. Open zoo + marine park, lunch available on site." },
  "d4-1-msg": { zh: "3歲女友想去動物園，但如果你不想也沒關係，就再看去哪裡，如果你超帥願意陪我去動物園，我再請助理訂車 🩵 我都可以", en: "My inner 3-year-old wants to go to the zoo — but it's okay if you'd rather not, we'll just figure something else out. If you're handsome enough to come with me, I'll have my assistant book the car 🩵 either way is fine with me" },
  "d4-2-h": { zh: "飯店休息 / 按摩", en: "Rest at the hotel / massage" },
  "d4-2-p": { zh: "不想外出的話，留在飯店休息，或加訂一次按摩。", en: "Stay in and rest, or book another massage, if you'd rather not go out." },
  "d4-3-h": { zh: "Dry Wave Cocktail Studio", en: "Dry Wave Cocktail Studio" },
  "d4-3-p": { zh: "50 Best #4，Thonglor 巷內，離飯店約 1-1.5 公里。傍晚時段去，不用特別訂位。", en: "Asia's 50 Best #4, tucked in a Thonglor alley, about 1-1.5 km from the hotel. Going in the early evening, no reservation needed." },
  "d4-4-p": { zh: "朋友聚餐，自行安排，時間留白。", en: "Dinner with friends, self-arranged, kept open." },
  "d5-title": { zh: "離開", en: "Departure" },
"d5-3-h": { zh: "Grace 前往機場", en: "Grace heads to the airport" },
  "d5-3-p": { zh: "曼谷飛桃園，10:50 起飛、15:30 到。國際線建議提早 3 小時，飯店到機場 40-60 分鐘，7 點前需出發。Hank 航班時間相近，可同行。", en: "Flying Bangkok → Taoyuan, departing 10:50 AM, landing 3:30 PM. International check-in wants 3 hours; 40-60 minutes hotel to airport — leave before 7 AM. Hank's flight is similar timing, can travel together." },
  "notes-h": { zh: "備忘", en: "Notes" },
"notes-1k": { zh: "住宿", en: "Staying at" },
  "notes-2k": { zh: "10/2 訂位", en: "Bookings, 10/2" },
  "notes-2v": { zh: "iODE 20:00・Bar Sathorn 22:00", en: "iODE 8:00 PM · Bar Sathorn 10:00 PM" },
  "notes-3k": { zh: "移動方式", en: "Getting around" },
  "notes-3v": { zh: "市區 BTS + Grab；Day 4 Safari World 需包車", en: "BTS + Grab within the city; Day 4's Safari World needs a hired car" },
  "notes-4k": { zh: "時間標示", en: "About the times" },
  "notes-4v": { zh: "淡黃色卡片為已訂位項目，其餘為建議順序", en: "Pale-yellow cards are confirmed reservations; everything else is a suggested order" },
  "notes-5k": { zh: "晚餐穿著", en: "Dinner dress code" },
  "notes-5v": { zh: "每天晚餐都穿輕便正裝（smart casual），不要太隨便", en: "Smart casual for dinner every night — not too casual" }
              };
